version: '1.0'

services:
  php:
    image: php:8.2-fpm
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www/html
    links:
      - php
  composer:
    image: composer
    command: install
    volumes:
      - "../:/app"