version: '3.7'

services:
  php:
    image: php:8.2-fpm
    depends_on:
      - composer
    volumes:
      - "../:/var/www/html/"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - "../:/var/www/html/"
    depends_on:
      - composer
      - php
  composer:
    image: composer/composer
    volumes:
      - "../composer:/app"
    command: install
